# Generated by Django 3.2.8 on 2022-01-27 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 1, 27))),
                ('approval', models.BooleanField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.students')),
            ],
        ),
        migrations.AddField(
            model_name='pendingrequests',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 27)),
        ),
        migrations.DeleteModel(
            name='RequestsStatus',
        ),
    ]
