# Generated by Django 3.2.8 on 2022-01-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20220127_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.departments'),
        ),
    ]
